server:
  port: 8081
spring:
  application:
    name: "CapacidadMc"
  devtools:
    add-properties: false
  profiles:
    include: null
  r2dbc:
    url: r2dbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}
    username: ${adapters.r2dbc.username}
    password: ${adapters.r2dbc.password}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}
    user: ${adapters.r2dbc.username}
    password: ${adapters.r2dbc.password}
    schemas: ${adapters.r2dbc.database}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
adapters:
  r2dbc:
    host: localhost
    port: 3306
    database: bootcamp-capacidad
    username: root
    password: andres98
